name: tests

on: [ push ]

env:
  DB_DRIVERNAME: mysql

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" , "3.9", "3.10" ]

    services:
      postgres:
        image: mysql:5.7
        env:
          DB_USER: test
          DB_NAME: unistest
          DB_PASSWORD: test
          DB_PORT: 3306
          DB_HOST: localhost
          DB_ROOT_PASSWORD: root

        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest
